# Generated by Django 5.1.7 on 2025-03-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reusable", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bot_Command",
        ),
        migrations.DeleteModel(
            name="Raya_Command",
        ),
    ]
