# Generated by Django 5.1.7 on 2025-03-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0008_group_task_reminder_active_alter_task_scope_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=31)),
                ("room_no", models.IntegerField(blank=True, null=True)),
                ("scannable", models.BooleanField(default=True)),
                ("is_open", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("open_from", models.TimeField(blank=True, null=True)),
                ("open_to", models.TimeField(blank=True, null=True)),
                ("close_from", models.TimeField(blank=True, null=True)),
                ("close_to", models.TimeField(blank=True, null=True)),
                (
                    "gate_keepers_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.group",
                    ),
                ),
            ],
        ),
    ]
