# Generated by Django 5.1.7 on 2025-04-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raya", "0001_initial"),
        ("user", "0008_group_task_reminder_active_alter_task_scope_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255)),
                (
                    "source_channel_id",
                    models.CharField(default="-1002653419335", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("propagated_at", models.DateTimeField(null=True)),
                ("is_general", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.group",
                    ),
                ),
            ],
        ),
    ]
