# Generated by Django 5.1.7 on 2025-03-20 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_doc_id", models.CharField(max_length=255, unique=True)),
                ("folder_id", models.CharField(max_length=255)),
                ("doc_code", models.CharField(max_length=6, unique=True)),
                ("is_finalized", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.telegramuser",
                    ),
                ),
            ],
        ),
    ]
