ACCEPT_JOIN_GROUP_COMMAND = "accept_join"
GIVE_ACCESS_COMMAND = "give_access"
REVOKE_ACCESS_COMMAND = "revoke_access"
REMOVE_USER_COMMAND = "remove_user"
LIST_GROUPS_COMMAND = "list_groups"
CANCEL_COMMAND = "cancel"
