# Generated by Django 5.1.7 on 2025-04-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_playlistaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="artist",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
