# Generated by Django 5.1.7 on 2025-03-21 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "telegram_chat_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="telegramuser",
            old_name="first_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="is_authorized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="user_type",
            field=models.CharField(
                choices=[("manager", "manager"), ("internal", "internal")],
                default="internal",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.telegramuser",
                    ),
                ),
            ],
        ),
    ]
