# Generated by Django 5.1.7 on 2025-03-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_group_rename_first_name_telegramuser_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="user_auth_state",
            field=models.CharField(
                choices=[
                    ("awaiting_email", "awaiting_email"),
                    ("awaiting_name", "awaiting_name"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
