# Generated by Django 5.1.7 on 2025-03-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_telegramuser_user_auth_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="user_auth_state",
            field=models.CharField(
                choices=[
                    ("awaiting_email", "awaiting_email"),
                    ("awaiting_name", "awaiting_name"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
