# Generated by Django 5.1.7 on 2025-03-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_telegramuser_user_auth_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="user_auth_state",
        ),
    ]
