# Generated by Django 5.1.7 on 2025-03-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_telegramuser_user_auth_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="chat_id",
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("very_high", "very_high"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("initial", "initial"),
                            ("taken", "taken"),
                            ("done", "done"),
                        ],
                        default="initial",
                        max_length=10,
                    ),
                ),
                (
                    "assignee_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="user.telegramuser",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_tasks",
                        to="user.telegramuser",
                    ),
                ),
                (
                    "scope_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.group",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope_group"], name="user_task_scope_g_3f1375_idx"
                    ),
                    models.Index(fields=["state"], name="user_task_state_e21555_idx"),
                    models.Index(
                        fields=["assignee_user"], name="user_task_assigne_ed6174_idx"
                    ),
                ],
                "unique_together": {("scope_group", "title")},
            },
        ),
    ]
