# Generated by Django 5.1.7 on 2025-03-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_group_chat_id_task"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("scope_group", "title", "created_at")},
        ),
    ]
