# Generated by Django 5.1.7 on 2025-03-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_task_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="task_reminder_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="scope_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="user.group",
            ),
        ),
    ]
